package cmd

import (
	"bytes"
	"strings"
	"testing"

	"github.com/otherjamesbrown/cobuild/internal/contextaudit"
)

func TestPrintAuditText_ExpandsOnlyFlaggedEntries(t *testing.T) {
	var buf bytes.Buffer
	printAuditText(&buf, &contextaudit.Report{
		RepoRoot: "/tmp/demo",
		Entries: []contextaudit.LayerEntry{
			{
				RelPath: ".cobuild/context/always/small.md",
				Bytes:   512,
			},
			{
				RelPath: ".cobuild/context/always/anatomy.md",
				Bytes:   45 * 1024,
				Flags:   []string{"very-large"},
				Annotation: &contextaudit.Annotation{
					Owner:    "cobuild — generated by `cobuild scan`",
					WhyLarge: "scanner indexed 12 directories; biggest sections are node_modules/ (~41.0K tokens)",
					TryHere: []string{
						"1. `cobuild scan --skip node_modules/,vendor/` then re-run dispatch",
						"2. Add the same paths to `.cobuild/scan.yaml`",
					},
					FileHere: "cobuild — if scan defaults still need tightening upstream",
				},
			},
		},
		TotalBytes:   45*1024 + 512,
		FlaggedCount: 1,
	})

	out := buf.String()
	for _, want := range []string{
		".cobuild/context/always/small.md",
		".cobuild/context/always/anatomy.md",
		"Owner:",
		"Why large:",
		"Try here:",
		"File here:",
		"`cobuild scan --skip node_modules/,vendor/`",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("output missing %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "Recommendations:") {
		t.Fatalf("legacy recommendations block should be gone:\n%s", out)
	}
}
