package contextaudit

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Annotation explains why a flagged file is large and what to do next.
type Annotation struct {
	Owner    string   `json:"owner,omitempty"`
	WhyLarge string   `json:"why_large,omitempty"`
	TryHere  []string `json:"try_here,omitempty"`
	FileHere string   `json:"file_here,omitempty"`
}

type ownerKind string

const (
	ownerCobuild   ownerKind = "cobuild"
	ownerProject   ownerKind = "project"
	ownerAmbiguous ownerKind = "ambiguous"
)

type ownerInfo struct {
	Kind       ownerKind
	Generator  string
	OwnerLabel string
	Project    string
	FileHere   string
}

type generatedFileHint struct {
	Path      string
	Generator string
	Owner     ownerKind
	FileHere  string
}

func annotateEntry(repoRoot string, entry LayerEntry, fullPath string, modTime time.Time, hints map[string]generatedFileHint) *Annotation {
	info := classifyOwner(repoRoot, entry, hints)
	return &Annotation{
		Owner:    formatOwner(info),
		WhyLarge: whyLarge(info, entry, fullPath, modTime),
		TryHere:  tryHere(info, entry, fullPath),
		FileHere: fileHere(info),
	}
}

func classifyOwner(repoRoot string, entry LayerEntry, hints map[string]generatedFileHint) ownerInfo {
	project := loadProjectName(repoRoot)
	rel := filepath.ToSlash(entry.RelPath)

	if hint, ok := hints[rel]; ok {
		return ownerInfo{
			Kind:       defaultOwnerKind(hint.Owner, ownerCobuild),
			Generator:  defaultString(hint.Generator, "skills/context-map.yaml"),
			OwnerLabel: defaultString(hint.Path, rel),
			Project:    project,
			FileHere:   hint.FileHere,
		}
	}

	switch {
	case filepath.Base(rel) == "anatomy.md":
		return ownerInfo{
			Kind:      ownerCobuild,
			Generator: "cobuild scan",
			Project:   project,
			FileHere:  "cobuild — if scan defaults still need tightening upstream",
		}
	case filepath.Base(rel) == "cobuild-version.md":
		return ownerInfo{
			Kind:      ownerCobuild,
			Generator: "cobuild",
			Project:   project,
			FileHere:  "cobuild — generated context should be narrowed upstream",
		}
	default:
		return ownerInfo{
			Kind:    ownerProject,
			Project: project,
		}
	}
}

func formatOwner(info ownerInfo) string {
	switch info.Kind {
	case ownerCobuild:
		if info.Generator != "" {
			return fmt.Sprintf("cobuild — generated by `%s`", info.Generator)
		}
		return "cobuild"
	case ownerAmbiguous:
		if info.Generator != "" {
			return fmt.Sprintf("%s + cobuild (mixed ownership; generator `%s`)", info.Project, info.Generator)
		}
		return fmt.Sprintf("%s + cobuild (mixed ownership)", info.Project)
	default:
		return fmt.Sprintf("%s (project-authored)", info.Project)
	}
}

func whyLarge(info ownerInfo, entry LayerEntry, fullPath string, modTime time.Time) string {
	if filepath.Base(entry.RelPath) == "anatomy.md" {
		if why := anatomyWhyLarge(fullPath); why != "" {
			return why
		}
	}

	lines := countLines(fullPath)
	date := modTime.UTC().Format("2006-01-02")
	age := approxAge(modTime)

	switch info.Kind {
	case ownerCobuild:
		if info.Generator != "" {
			return fmt.Sprintf("generated by `%s`; %d lines as of %s (%s)", info.Generator, lines, date, age)
		}
		return fmt.Sprintf("generated content; %d lines as of %s (%s)", lines, date, age)
	case ownerAmbiguous:
		return fmt.Sprintf("%d lines; last updated %s (%s); ownership is mixed between project content and generated output", lines, date, age)
	default:
		return fmt.Sprintf("%d lines; last updated %s (%s)", lines, date, age)
	}
}

func tryHere(info ownerInfo, entry LayerEntry, fullPath string) []string {
	if filepath.Base(entry.RelPath) == "anatomy.md" {
		skips := anatomySuggestedSkips(fullPath)
		skipArg := "<dir1>,<dir2>"
		if len(skips) > 0 {
			skipArg = strings.Join(skips, ",")
		}
		return []string{
			fmt.Sprintf("1. `cobuild scan --skip %s` then re-run dispatch", skipArg),
			"2. Add the same paths to `.cobuild/scan.yaml` (or legacy `.cobuild/scan-exclude`); see `docs/guides/context-optimization.md`",
		}
	}

	switch info.Kind {
	case ownerCobuild:
		return []string{
			"1. Reduce the generator output or move it out of `always/` into a narrower phase bucket",
			"2. See `docs/guides/context-optimization.md` before filing upstream",
		}
	case ownerAmbiguous:
		return []string{
			"1. Trim the file locally first; if it is regenerated, tighten the generator instead of hand-editing around it",
			"2. If ownership stays unclear, update `skills/context-map.yaml` or file an upstream cobuild follow-up",
		}
	default:
		return []string{
			"1. Edit the file directly; move historical or reference-heavy content to `docs/` or a narrower phase bucket",
			"2. See `docs/guides/context-optimization.md` for trimming patterns",
		}
	}
}

func fileHere(info ownerInfo) string {
	if info.FileHere != "" {
		return info.FileHere
	}
	switch info.Kind {
	case ownerCobuild:
		return "cobuild"
	case ownerAmbiguous:
		return "local project or cobuild — depends on whether the file is hand-maintained or generator-owned"
	default:
		return "(N/A — local fix)"
	}
}

type anatomySection struct {
	Name   string
	Tokens int
}

func anatomyWhyLarge(fullPath string) string {
	sections, err := parseAnatomySections(fullPath)
	if err != nil || len(sections) == 0 {
		return ""
	}

	sort.Slice(sections, func(i, j int) bool {
		if sections[i].Tokens == sections[j].Tokens {
			return sections[i].Name < sections[j].Name
		}
		return sections[i].Tokens > sections[j].Tokens
	})

	top := sections
	if len(top) > 3 {
		top = top[:3]
	}
	var largest []string
	for _, section := range top {
		largest = append(largest, fmt.Sprintf("%s (~%s tokens)", anatomySectionLabel(section.Name), formatTokens(section.Tokens)))
	}

	skippable := anatomyLikelySkippableDirs(sections)
	if len(skippable) > 0 {
		return fmt.Sprintf("scanner indexed %d directories; biggest sections are %s; likely scan-skippable: %s",
			len(sections), strings.Join(largest, ", "), strings.Join(skippable, ", "))
	}
	return fmt.Sprintf("scanner indexed %d directories; biggest sections are %s; no obvious scan-skippable directories were indexed",
		len(sections), strings.Join(largest, ", "))
}

func anatomySuggestedSkips(fullPath string) []string {
	sections, err := parseAnatomySections(fullPath)
	if err != nil {
		return nil
	}
	return anatomyLikelySkippableDirs(sections)
}

func anatomyLikelySkippableDirs(sections []anatomySection) []string {
	matchers := []string{
		"vendor", "node_modules", "generated", "build", "dist", "out", "coverage",
		"htmlcov", "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache",
		".cache", "target", "tmp", ".next", ".nuxt", "data/raw", "gen",
	}

	seen := map[string]bool{}
	var out []string
	for _, section := range sections {
		name := strings.TrimSuffix(section.Name, "/")
		lower := strings.ToLower(name)
		for _, candidate := range matchers {
			if lower == candidate || strings.HasSuffix(lower, "/"+candidate) || strings.Contains(lower, candidate+"/") {
				label := anatomySectionLabel(section.Name)
				if !seen[label] {
					seen[label] = true
					out = append(out, label)
				}
				break
			}
		}
	}
	sort.Strings(out)
	if len(out) > 3 {
		out = out[:3]
	}
	return out
}

func parseAnatomySections(fullPath string) ([]anatomySection, error) {
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return nil, err
	}

	var sections []anatomySection
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "## ") || !strings.Contains(line, "(~") || !strings.Contains(line, " tokens)") {
			continue
		}
		name, tokenText, ok := splitAnatomyHeading(line)
		if !ok {
			continue
		}
		tokens, err := parseTokenEstimate(tokenText)
		if err != nil {
			continue
		}
		sections = append(sections, anatomySection{Name: name, Tokens: tokens})
	}
	return sections, nil
}

func splitAnatomyHeading(line string) (name string, tokenText string, ok bool) {
	body := strings.TrimPrefix(line, "## ")
	idx := strings.LastIndex(body, " (~")
	if idx < 0 || !strings.HasSuffix(body, " tokens)") {
		return "", "", false
	}
	name = strings.TrimSpace(body[:idx])
	tokenText = strings.TrimSuffix(strings.TrimPrefix(body[idx:], " (~"), " tokens)")
	return name, tokenText, true
}

func parseTokenEstimate(raw string) (int, error) {
	raw = strings.TrimSpace(strings.TrimSuffix(strings.ToUpper(raw), "TOK"))
	multiplier := 1.0
	if strings.HasSuffix(raw, "K") {
		multiplier = 1000
		raw = strings.TrimSuffix(raw, "K")
	}
	value, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		return 0, err
	}
	return int(math.Round(value * multiplier)), nil
}

func anatomySectionLabel(name string) string {
	name = strings.TrimSpace(name)
	if name == "Root" {
		return "Root"
	}
	if strings.HasSuffix(name, "/") {
		return name
	}
	return name + "/"
}

func formatTokens(tokens int) string {
	if tokens >= 1000 {
		return fmt.Sprintf("%.1fK", float64(tokens)/1000)
	}
	return strconv.Itoa(tokens)
}

func countLines(fullPath string) int {
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return 0
	}
	if len(data) == 0 {
		return 0
	}
	return strings.Count(string(data), "\n") + 1
}

func approxAge(t time.Time) string {
	days := int(time.Since(t).Hours() / 24)
	switch {
	case days < 1:
		return "updated today"
	case days == 1:
		return "about 1 day old"
	default:
		return fmt.Sprintf("about %d days old", days)
	}
}

func loadProjectName(repoRoot string) string {
	data, err := os.ReadFile(filepath.Join(repoRoot, ".cobuild.yaml"))
	if err == nil {
		var cfg struct {
			Project string `yaml:"project"`
		}
		if yaml.Unmarshal(data, &cfg) == nil && strings.TrimSpace(cfg.Project) != "" {
			return strings.TrimSpace(cfg.Project)
		}
	}

	name := filepath.Base(repoRoot)
	if name == "." || name == string(filepath.Separator) || name == "" {
		return "project"
	}
	return name
}

func loadContextMap(repoRoot string) map[string]generatedFileHint {
	path := filepath.Join(repoRoot, "skills", "context-map.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil
	}

	out := map[string]generatedFileHint{}
	for _, key := range []string{"generated", "generated_files"} {
		items, ok := raw[key].([]any)
		if !ok {
			continue
		}
		for _, item := range items {
			hint, ok := parseGeneratedFileHint(item)
			if !ok || hint.Path == "" {
				continue
			}
			hint.Path = filepath.ToSlash(strings.TrimSpace(hint.Path))
			out[hint.Path] = hint
		}
	}
	return out
}

func parseGeneratedFileHint(raw any) (generatedFileHint, bool) {
	switch value := raw.(type) {
	case string:
		return generatedFileHint{Path: value, Generator: "skills/context-map.yaml", Owner: ownerCobuild}, true
	case map[string]any:
		hint := generatedFileHint{
			Path:      firstNonEmptyString(value["path"], value["file"], value["rel_path"]),
			Generator: firstNonEmptyString(value["generator"], value["source"]),
			FileHere:  firstNonEmptyString(value["file_here"]),
		}
		switch strings.ToLower(strings.TrimSpace(firstNonEmptyString(value["owner"], value["ownership"]))) {
		case "project":
			hint.Owner = ownerProject
		case "ambiguous", "mixed":
			hint.Owner = ownerAmbiguous
		default:
			hint.Owner = ownerCobuild
		}
		return hint, hint.Path != ""
	default:
		return generatedFileHint{}, false
	}
}

func firstNonEmptyString(values ...any) string {
	for _, value := range values {
		s, ok := value.(string)
		if ok && strings.TrimSpace(s) != "" {
			return strings.TrimSpace(s)
		}
	}
	return ""
}

func defaultString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func defaultOwnerKind(value ownerKind, fallback ownerKind) ownerKind {
	if value == "" {
		return fallback
	}
	return value
}
